### GET all students
GET http://localhost:8080/api/students

### POST create student
POST http://localhost:8080/api/students
Content-Type: application/json

{
  "fullName": "test",
  "email": "test@mail,ru"
}

### PUT subscribe student to courses
PUT http://localhost:8080/api/students
Content-Type: application/json

{
  "id": "-501445707849795810",
  "selectedCourses": ["Java"]
}