server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/prod_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
logging:
  level:
    org.springframework.jdbc.core: warn
    liquibase: warn
