server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
      show-components: always

spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/prod_db
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.xml
    contexts: production
logging:
  level:
    org.springframework.jdbc.core: warn
    liquibase: warn