spring:
  datasource:
    url: jdbc:postgresql://localhost:5454/test_db
    username: test_user
    password: 1234
    driver-class-name: org.postgresql.Driver
  liquibase:
    contexts: sandbox
logging:
  level:
    org.springframework.jdbc.core: info